### ISSUE TITLE
Parameters Tab

### ISSUE THREAD

**Issue by katduecker** [Kaanwoj/shinyTWIN#5]
- same slider names as in simulation tab
- put the two plots for the first stage into one plot
- add legends to plots
- add normal and uniform distribution to drop down menu

**Comment by SpindM** [comment]
- changed the slider names
- added normal + uniform distribution to the drop down menu (but the plots dont work yet)
- put the two plots together. Both plots are doing the exact same thing, so when you put both sliders to an identical position, then you only see one line because they're at the same position.
- _Question 1:_ Does this plot make sense?
- _Question 2:_ We could also use ggplot2 or something for the graphs? Might look neater and legends are included automatically (Afaik).. ;)  
- _Question 3:_ Do we want to have the standard deviation as a slider option? (Is implemented in Parameters tab, but not in Simulation tab, and does not really change the graphs..)

**Comment by Kaanwoj** [comment]
_Answer to question 1_: Yes, because for the same mean processing time A and V have the same distribution.
_Answer to question 2_: Sure, try it out ;)
_Answer to question 3_: Do you mean the 2nd stage SD? I'd say we could add a slider for it in the Simulation tab.

Small note on communication: in the future, please write what you changed (e.g. your first three bullet points) also into the body of the commit message. See this guide on how to write good commit messages: https://chris.beams.io/posts/git-commit/
